  name: MineQuaft-Plugin
  main: de.kevinius.minequaft.main.Main
  version: "1.0.4"
  api-version: "1.16"

  commands:
    MineQuaft-give:
      description: gives you items from the MineQuaft plugin!